# Generated by Django 4.1.4 on 2022-12-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_id',
            field=models.CharField(default='https://www.youtube.com/embed/dQw4w9WgXcQ', max_length=55),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(max_length=255),
        ),
    ]
