# Generated by Django 4.1.4 on 2022-12-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0004_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='static/avatars'),
        ),
    ]
