# Generated by Django 4.1.4 on 2022-12-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creators', '0005_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/avatars/default.jpg', upload_to='static/avatars'),
        ),
    ]
