# Generated by Django 4.1.4 on 2022-12-17 04:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creators', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes_counter',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
